name: Build and Release FanControl Plugin

on:
  push:
    tags:
      - '*'  # Trigger on any tag
  workflow_dispatch:

env:
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: msbuild FanControl.ClevoPlugin.sln /t:Restore

      - name: Build ClevoPlugin (AnyCPU)
        run: msbuild FanControl.ClevoPlugin.sln /p:Configuration=${{ env.CONFIGURATION }} /p:Platform="Any CPU" /t:Build /p:BuildProjectReferences=false /p:Projects="ClevoPlugin\\ClevoPlugin.csproj"

      - name: Build ControlServer (x86)
        run: msbuild FanControl.ClevoPlugin.sln /p:Configuration=${{ env.CONFIGURATION }} /p:Platform="x86" /t:Build /p:BuildProjectReferences=false /p:Projects="ControlServer\\ControlServer.csproj"

      - name: Copy ControlServer output to ClevoPlugin /Server subfolder
        run: |
          $clevoPath = "ClevoPlugin\\bin\\${{ env.CONFIGURATION }}"
          $controlPath = "ControlServer\\bin\\x86\\${{ env.CONFIGURATION }}"
          $destServerPath = "$clevoPath\\Server"
          New-Item -ItemType Directory -Force -Path $destServerPath
          Copy-Item "$controlPath\\*" -Destination $destServerPath -Recurse -Force
        shell: pwsh

      - name: Prepare Zip
        run: |
          mkdir build_output
          Copy-Item "ClevoPlugin\\bin\\${{ env.CONFIGURATION }}\\*" -Destination "build_output\\" -Recurse -Force
          Compress-Archive -Path build_output\\* -DestinationPath FanControlPlugin.zip
        shell: pwsh

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: FanControlPlugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
